# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        # filter name
        logo_thumb:
            filter:
                thumbnail:
                    size: [400, 51]
                    mode: outbound
    
        squared_thumb_normal:
            filters:
                thumbnail:
                    size: [540, 540]
                    mode: outbound

        squared_thumb_medium:
            filters:
                thumbnail:
                    size: [253, 253]
                    mode: outbound

        squared_thumb_small:
            filters:
                thumbnail:
                    size: [180, 180]
                    mode: outbound

        squared_thumb_smaller:
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        squared_thumb_xsmall:
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
