# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        # Filter for the logo
        rectangular_logo_thumb:
            filters:
                thumbnail:
                    size: [300, 43]
                    mode: outbound
        # Filter for the carousel
        carousel_container_thumb:
            filters:
                thumbnail:
                    size: [1110, 413]
                    mode: outbound
        # Filters for the about us page
        rectangular_img_thumb:
            filters:
                thumbnail:
                    size: [512, 342]
                    mode: outbound
        rectangular_thumb_small:
            filters:
                thumbnail:
                    size: [150, 60]
                    mode: outbound
        # Filter for the publication page
        rectangular_publication_thumb:
            filters:
                thumbnail:
                    size: [900, 300]
                    mode: outbound
        # Filters for squared thumbnail
        squared_thumb_normal:
            filters:
                thumbnail:
                    size: [540, 540]
                    mode: outbound

        squared_thumb_medium:
            filters:
                thumbnail:
                    size: [253, 253]
                    mode: outbound

        squared_thumb_small:
            filters:
                thumbnail:
                    size: [160, 160]
                    mode: outbound

        squared_thumb_smaller:
            filters:
                thumbnail:
                    size: [128, 128]
                    mode: outbound

        squared_thumb_xsmall:
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
