vich_uploader:
   db_driver: orm

   mappings:
      publication_image:
         uri_prefix: /uploads/publications
         upload_destination: "%kernel.project_dir%/public/uploads/publications"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         # Configure the lifecycle events
         inject_on_load: false
         delete_on_update: true
         delete_on_remove: true

      formation_image:
         uri_prefix: /uploads/formations
         upload_destination: "%kernel.project_dir%/public/uploads/formations"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         # Configure the lifecycle events
         inject_on_load: false
         delete_on_update: true
         delete_on_remove: true

      client_image:
         uri_prefix: /uploads/clients
         upload_destination: "%kernel.project_dir%/public/uploads/clients"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         # Configure the lifecycle events
         inject_on_load: false
         delete_on_update: true
         delete_on_remove: true

      partenaire_image:
         uri_prefix: /uploads/partenaires
         upload_destination: "%kernel.project_dir%/public/uploads/partenaires"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         # Configure the lifecycle events
         inject_on_load: false
         delete_on_update: true
         delete_on_remove: true
